[build]
  publish = "out"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/.netlify/functions/generate-delphic"
  name = "generate-delphic"

[[scheduled]]
  name = "generate-delphic"
  schedule = "0 */2 * * *"
