[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[scheduled]]
  path = "/.netlify/functions/generate-delphic"
  schedule = "0 */2 * * *"
