[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "functions-src"
  node_bundler = "esbuild"

[[scheduled.functions]]
  path = "/.netlify/functions/generate-delphic"
  schedule = "*/30 13-19 * * 1-5"


